services:
  myPizzeriaDB:
    image: mysql:oracle
    container_name: my-pizzeria
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=pizzeria-db
      - MYSQL_USER=test1
      - MYSQL_PASSWORD=123456
    volumes:
      - ./mysql:/var/lib/mysql
#    labels:
#      org.springframework.boot.ignore: true
